deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
  containers:
    - name: orchestrator
      image:
        repository: flaminel/orchestrator
        tag: latest
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 500m
          memory: 128Mi
      envFromSecret:
        - secretName: connections-secret
          envs:
            - name: ConnectionStrings__Orchestrator
              key: orchestratorDb
            - name: RabbitMqConfig__Host
              key: rabbitMqHost
            - name: RabbitMqConfig__Username
              key: rabbitMqUser
            - name: RabbitMqConfig__Password
              key: rabbitMqPassword

secrets:
  - name: connections-secret
    type: Opaque
    data:
      orchestratorDb: server=$MySQLHost;port=3306;database=orchestrator;uid=$MySQLUser;pwd='$MySQLPassword';sslMode=Required
      rabbitMqHost: $RabbitMQHost
      rabbitMqUser: $RabbitMQUsername
      rabbitMqPassword: $RabbitMQPassword