on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: flmorg/universal-workflows/.github/workflows/dotnet.build.app.yml@main
    with:
      dockerRepository: flaminel/orchestrator
      githubContext: ${{ toJSON(github) }}
    secrets: inherit